# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
